name: Testing
on:
  push:
    branches:
      - main
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
env:
  RUST_TOOLCHAIN: stable
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          cargo test
